#!/usr/bin/env python
# coding: utf-8

# # **Movie Recommender Systems**

# Collection of data has led to a new era of information.It is being used to build creative system and this is where Recommendation Systems come into play.
# Recommendation Systems are information filtering systems they provides items that are more relevant to the search item or are realted to the search history of the user.  
# 

# Companies like Amazon Prime and Spotify  depend highly on the effectiveness of their recommendation system for their business and suceess.

# We will be building Movie Recommendation System 

# There will be 2 recommender systems example:-
# 
# > *  **Demographic Filtering**- They offer generalized recommendations to every user, based on movie popularity and/or genre. The System recommends the same movies to users with similar demographic features. Since each user is different , this approach is considered to be too simple. The basic idea behind this system is that movies that are more popular and critically acclaimed will have a higher probability of being liked by the average audience.
# 
# 

# > *  **Content Based Filtering**- They suggest similar items based on a particular item. This system uses item metadata, such as genre, director, description, actors, etc. for movies, to make these recommendations. The general idea behind these recommender systems is that if a person liked a particular item, he or she will also like an item that is similar to it.

# Start

# In[1]:


#importing the required library

import pandas as pd 
import numpy as np 


# In[2]:


#importing the dataset and assigning it to variables

credits_df = pd.read_csv('tmdb_5000_credits.csv')
movies_df = pd.read_csv('tmdb_5000_movies.csv')


# data

# In[3]:


movies_df.head(2)


# In[4]:


#watching starting 2 rows in dataset
credits_df.head(2)


# The credit dataset contains the following features:-
# 
# * movie_id - A unique identifier for each movie.
# * cast - Actors in movie.
# * crew - The name of Director, Editor, Composer, Writer etc.
# 
# The movies dataset has the following features:- 
# 
# * budget - Making cost.
# * genre - The genre of the movie, Action, Comedy ,Thriller etc.
# * homepage - link to the homepage of movie.
# * id - A unique identifier for each movie.
# * keywords - The keywords or tags related to the movie.
# * original_language - language in which the movie was made.
# * original_title - The title of the movie before translation or adaptation.
# * overview - A brief description of the movie.
# * popularity - A numeric quantity specifying the movie popularity.
# * production_companies - The production house of the movie.
# * production_countries - The country in which it was produced.
# * release_date - The date on which it was released.
# * revenue - The worldwide revenue generated by the movie.
# * runtime - The running time of the movie in minutes.
# * status - "Released" or "Rumored".
# * tagline - Movie's tagline.
# * title - Title of the movie.
# * vote_average -  average ratings the movie recieved.
# * vote_count - the count of votes recieved.
# 

# In[5]:


# changing- the column name from movie_id to id

credits_df.columns = ['id','tittle','cast','crew']


# In[6]:


# merging the two data frame on id column

movies_df= movies_df.merge(credits_df,on='id')


# In[7]:


movies_df.head(2)


# Data Preprosessing

# In[8]:


#droping the column which are un-required

movies_df = movies_df.drop(columns=['budget','homepage', 'status','production_countries'])
movies_df = movies_df.drop(columns=['original_language', 'runtime'])


# In[9]:


movies_df.head(2)


# ## **Demographic Filtering** -
#    
# * 1. We need a metric/parameter to score or rate movie 
# * 2. Calculate the score for every movie 
# * 3. Sort the scores and recommend the best rated movie to the users.
# 
# 
# IMDB's weighted rating (wr) formula : 
# 
# ![](https://image.ibb.co/jYWZp9/wr.png)
# where,
# * v : the number of votes for the movie
# * m : the minimum votes required to be listed in the chart
# * R : the average rating of the movie
# * C : the mean of all vote across the whole report
# 
# We have v as **vote_count** and
#         R as **vote_average**
# 
# Note : Average ratings of the movie is not good to pick as a parameter because if a movie have 1 review of full rating then its        Average rating will be highest

# In[10]:


C = movies_df['vote_average'].mean()
C
#the mean rating for all the movies is approx 6 on a scale of 10


# 

# In[11]:


# Determine an appropriate value for m, the minimum votes required to be listed in the chart
# We will use 90th percentile as our cutoff
# for a movie to feature in the charts, it must have more votes than at least 90% of the movies in the list.

m = movies_df['vote_count'].quantile(0.9)
m


# In[ ]:





# 

# In[12]:


#                               vote_count row having vote > m from movies dataframe  will only to the chart

top_movies_chart = movies_df.copy().loc[movies_df['vote_count'] >= m]
top_movies_chart.shape


# In[45]:


# We see that there are 481 movies which qualify to be in this list
# Now, we need to calculate our metric for each qualified movie.
# We will define a function, weighted_rating() and define a new feature score
# we'll calculate the value by applying this function to our DataFrame of qualified movies

top_movies_chart.head(2)


# 

# In[13]:


def weighted_rating(x, m=m, C=C):
    v = x['vote_count']
    R = x['vote_average']
    # Calculation based on the IMDB formula
    return (v/(v+m) * R) + (m/(m+v) * C)


# In[14]:


# Define a new feature 'score' and calculate its value with `weighted_rating()`

top_movies_chart['score'] = top_movies_chart.apply(weighted_rating, axis=1)

# Finally, let's sort the DataFrame (chart) based on the score feature
# output the title, vote count, vote average and weighted rating or score of the top 10 movies


# 

# In[15]:


#Sort movies based on score calculated above
top_movies_chart = top_movies_chart.sort_values('score', ascending=False)


# In[ ]:



#Print the top 15 movies
top_movies_chart[['title', 'vote_count', 'vote_average', 'score']].head(10)


# We have made our first simple recommender. 
# It is can be used in  **Trending Now** tab of these systems we find movies that are very popular and they can just be obtained by sorting the dataset by the popularity column.

# In[48]:


popularity_chart = movies_df.sort_values('popularity', ascending=False)
import matplotlib.pyplot as plt

# bar plot(x,y)
plt.barh( popularity_chart['title'].head(6), popularity_chart['popularity'].head(6) )

plt.gca().invert_yaxis()
plt.xlabel("Popularity")
plt.title("Popular Movies")


# These demographic recommender provide a general chart of recommended movies to all the users.
# They are not sensitive to the interests of a particular user.
# This is when we move on to a more refined system-  Content Basesd Filtering.
# This uses the search history of the user to give recommendation

# # **Content Based Filtering**
# In this recommender system the content in the movie like overview, cast, crew, keyword, tagline etc. Is used to find its similarity with other movies. Then the movies that are most likely to be similar are recommended.
# 
# 

# ## **Plot description based Recommender**
# 
# We will compute pairwise similarity scores for all movies based on their plot descriptions and recommend movies based on that similarity score. The plot description is given in the **overview** feature of our dataset. 
# Let's take a look at the data. .. 

# In[49]:


movies_df['overview'].head(5)

#For any of you who has done even a  bit of text processing before knows we need to convert the word vector of each overview.
#Now we'll compute Term Frequency-Inverse Document Frequency (TF-IDF) vectors for each overview.

#Now if you are wondering what is term frequency , it is the relative frequency of a word in a document and is given as
 #  **(term instances/total instances)**.
#Inverse Document Frequency is the relative count of documents containing the term is given as 
#**log(number of documents/documents with term)**
#The overall importance of each word to the documents in which they appear is equal to **TF * IDF**

#This will give you a matrix where each column represents a word in the overview vocabulary (all the words that appear in at least one document) and each row represents a movie, as before.This is done to reduce the importance of words that occur frequently in plot overviews and therefore, their significance in computing the final similarity score.

#Fortunately, scikit-learn gives you a built-in TfIdfVectorizer class that produces the TF-IDF matrix in a couple of lines. That's great, isn't it? 
# In[52]:


#Import TfIdfVectorizer from scikit-learn
from sklearn.feature_extraction.text import TfidfVectorizer

#Define a TF-IDF Vectorizer Object. Remove all english stop words such as 'the', 'a'
tfidf = TfidfVectorizer(stop_words='english')

#Replace NaN with an empty string
movies_df['overview'] = movies_df['overview'].fillna('')

#Construct the required TF-IDF matrix by fitting and transforming the data
tfidf_matrix = tfidf.fit_transform(movies_df['overview'])

#Output the shape of tfidf_matrix
tfidf_matrix.shape


# We see that over 20,000 different words were used to describe the 4800 movies in our dataset.
# 
# With this matrix in hand, we can now compute a similarity score. There are several candidates for this; such as the euclidean, the Pearson and the [cosine similarity scores](https://en.wikipedia.org/wiki/Cosine_similarity). There is no right answer to which score is the best. Different scores work well in different scenarios and it is often a good idea to experiment with different metrics.
# 
# We will be using the cosine similarity to calculate a numeric quantity that denotes the similarity between two movies. We use the cosine similarity score since it is independent of magnitude and is relatively easy and fast to calculate. Mathematically, it is defined as follows:

# Since we have used the TF-IDF vectorizer, calculating the dot product will directly give us the cosine similarity score. Therefore, we will use sklearn's **linear_kernel()** instead of cosine_similarities() since it is faster.

# In[19]:


# Import linear_kernel
from sklearn.metrics.pairwise import linear_kernel

# Compute the cosine similarity matrix
cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)


# We are going to define a function that takes in a movie title as an input and outputs a list of the 10 most similar movies. Firstly, for this, we need a reverse mapping of movie titles and DataFrame indices. In other words, we need a mechanism to identify the index of a movie in our metadata DataFrame, given its title.

# In[20]:


#Construct a reverse map of indices and movie titles
indices = pd.Series(movies_df.index, index=movies_df['title']).drop_duplicates()


# We are now in a good position to define our recommendation function. These are the following steps we'll follow :-
# * Get the index of the movie given its title.
# * Get the list of cosine similarity scores for that particular movie with all movies. Convert it into a list of tuples where the first element is its position and the second is the similarity score.
# * Sort the aforementioned list of tuples based on the similarity scores; that is, the second element.
# * Get the top 10 elements of this list. Ignore the first element as it refers to self (the movie most similar to a particular movie is the movie itself).
# * Return the titles corresponding to the indices of the top elements.

# In[21]:


# Function that takes in movie title as input and outputs most similar movies
def get_recommendations(title, cosine_sim=cosine_sim):
    # Get the index of the movie that matches the title
    idx = indices[title]

    # Get the pairwsie similarity scores of all movies with that movie
    sim_scores = list(enumerate(cosine_sim[idx]))

    # Sort the movies based on the similarity scores
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # Get the scores of the 10 most similar movies
    sim_scores = sim_scores[1:11]

    # Get the movie indices
    movie_indices = [i[0] for i in sim_scores]

    # Return the top 10 most similar movies
    return movies_df['title'].iloc[movie_indices]


# In[22]:


get_recommendations('Superman')


# In[23]:


get_recommendations('Need for Speed')


# While our system has done a decent job of finding movies with similar plot descriptions, the quality of recommendations is not that great. "The Dark Knight Rises" returns all Batman movies while it is more likely that the people who liked that movie are more inclined to enjoy other Christopher Nolan movies. This is something that cannot be captured by the present system.

# ## **Credits, Genres and Keywords Based Recommender**
# It goes without saying that the quality of our recommender would be increased with the usage of better metadata. That is exactly what we are going to do in this section. We are going to build a recommender based on the following metadata: the 3 top actors, the director, related genres and the movie plot keywords.
# 
# From the cast, crew and keywords features, we need to extract the three most important actors, the director and the keywords associated with that movie. Right now, our data is present in the form of "stringified" lists , we need to convert it into a safe and usable structure

# In[24]:


# Parse the stringified features into their corresponding python objects
from ast import literal_eval

features = ['cast', 'crew', 'keywords', 'genres']
for feature in features:
    movies_df[feature] = movies_df[feature].apply(literal_eval)


# Next, we'll write functions that will help us to extract the required information from each feature.

# In[25]:


# Get the director's name from the crew feature. If director is not listed, return NaN
def get_director(x):
    for i in x:
        if i['job'] == 'Director':
            return i['name']
    return np.nan


# In[26]:


# Returns the list top 3 elements or entire list; whichever is more.
def get_list(x):
    if isinstance(x, list):
        names = [i['name'] for i in x]
        #Check if more than 3 elements exist. If yes, return only first three. If no, return entire list.
        if len(names) > 3:
            names = names[:3]
        return names

    #Return empty list in case of missing/malformed data
    return []


# In[27]:


# Define new director, cast, genres and keywords features that are in a suitable form.
movies_df['director'] = movies_df['crew'].apply(get_director)

features = ['cast', 'keywords', 'genres']
for feature in features:
    movies_df[feature] = movies_df[feature].apply(get_list)


# In[28]:


# Print the new features of the first 3 films
movies_df[['title', 'cast', 'director', 'keywords', 'genres']].head(3)


# The next step would be to convert the names and keyword instances into lowercase and strip all the spaces between them. This is done so that our vectorizer doesn't count the Johnny of "Johnny Depp" and "Johnny Galecki" as the same.

# In[29]:


# Function to convert all strings to lower case and strip names of spaces
def clean_data(x):
    if isinstance(x, list):
        return [str.lower(i.replace(" ", "")) for i in x]
    else:
        #Check if director exists. If not, return empty string
        if isinstance(x, str):
            return str.lower(x.replace(" ", ""))
        else:
            return ''


# In[30]:


# Apply clean_data function to your features.
features = ['cast', 'keywords', 'director', 'genres']

for feature in features:
    movies_df[feature] = movies_df[feature].apply(clean_data)


# We are now in a position to create our "metadata soup", which is a string that contains all the metadata that we want to feed to our vectorizer (namely actors, director and keywords).

# In[31]:


def create_soup(x):
    return ' '.join(x['keywords']) + ' ' + ' '.join(x['cast']) + ' ' + x['director'] + ' ' + ' '.join(x['genres'])
movies_df['soup'] = movies_df.apply(create_soup, axis=1)


# The next steps are the same as what we did with our plot description based recommender. One important difference is that we use the **CountVectorizer()** instead of TF-IDF. This is because we do not want to down-weight the presence of an actor/director if he or she has acted or directed in relatively more movies. It doesn't make much intuitive sense.

# In[32]:


# Import CountVectorizer and create the count matrix
from sklearn.feature_extraction.text import CountVectorizer

count = CountVectorizer(stop_words='english')
count_matrix = count.fit_transform(movies_df['soup'])


# In[33]:


# Compute the Cosine Similarity matrix based on the count_matrix
from sklearn.metrics.pairwise import cosine_similarity

cosine_sim2 = cosine_similarity(count_matrix, count_matrix)


# In[34]:


# Reset index of our main DataFrame and construct reverse mapping as before
movies_df = movies_df.reset_index()
indices = pd.Series(movies_df.index, index=movies_df['title'])


# We can now reuse our **get_recommendations()** function by passing in the new **cosine_sim2** matrix as your second argument.

# In[35]:


get_recommendations('The Dark Knight Rises', cosine_sim2)


# In[36]:


get_recommendations('The Godfather', cosine_sim2)


# We see that our recommender has been successful in capturing more information due to more metadata and has given us (arguably) better recommendations. It is more likely that Marvels or DC comics fans will like the movies of the same production house. Therefore, to our features above we can add *production_company* . 
# We can also increase the weight of the director , by adding the feature multiple times in the soup.
